language: node_js
node_js:
  - "node"
  - "lts/*"
  - "8"

script:
  - npm test

jobs:
  include:
    - stage: ESLint & BrowserStack
      node_js: node
      script:
        - npm run lint
        - npm run test:browsers
    - stage: test
